services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: denis
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myDb
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

volumes:
  postgres-data:
